---

apiVersion: civo.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: provider-civo
spec:
  region: lon1
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: civo-provider-secret
      key: credentials
