---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-crossplane-service
  namespace: keptn
  labels:
    name: keptn-crossplane-service
---
# Source: openebs/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptn-crossplane-service
  labels:
    name: keptn-crossplane-service
rules:
- apiGroups: ["","cluster.civo.crossplane.io","devopstoolkitseries.com"]
  resources: ["*"]
  verbs: ["create","delete","get","list","patch","update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keptn-crossplane-service
  labels:
    name: keptn-crossplane-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keptn-crossplane-service
subjects:
- kind: ServiceAccount
  name: keptn-crossplane-service
  namespace: keptn
---
# Deployment of our crossplane-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crossplane-service
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: crossplane-service
  replicas: 1
  template:
    metadata:
      labels:
        run: crossplane-service
        app.kubernetes.io/name: crossplane-service
        app.kubernetes.io/version: dev
    spec:
      containers:
        - name: crossplane-service
          image: keptnsandbox/crossplane-service # Todo: Replace this with your image name
          ports:
            - containerPort: 8080
          env:
            - name: CONFIGURATION_SERVICE
              value: 'http://configuration-service:8080'
        - name: distributor
          image: keptn/distributor:0.8.7
          livenessProbe:
            httpGet:
              path: /health
              port: 10999
            initialDelaySeconds: 5
            periodSeconds: 5
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "16Mi"
              cpu: "25m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          env:
            - name: PUBSUB_URL
              value: 'nats://keptn-nats-cluster'
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.event.environment-setup.>,sh.keptn.event.environment-teardown.>'
            - name: PUBSUB_RECIPIENT
              value: '127.0.0.1'
            - name: VERSION
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: 'metadata.labels[''app.kubernetes.io/version'']'
            - name: K8S_DEPLOYMENT_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: 'metadata.labels[''app.kubernetes.io/name'']'
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
      serviceAccountName: keptn-crossplane-service
---
# Expose crossplane-service via Port 8080 within the cluster
apiVersion: v1
kind: Service
metadata:
  name: crossplane-service
  namespace: keptn
  labels:
    run: crossplane-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: crossplane-service

