apiVersion: "spec.keptn.sh/0.2.0"
kind: "Shipyard"
metadata:
  name: "keptn-crossplane"
spec:
  stages:
    - name: "perf-test"
      sequences:
        - name: "delivery"
          tasks:
            - name: "environment-setup"
              properties:
                size: "medium"
            - name: "deployment"
              properties:
                deploymentstrategy: "user_managed"
            - name: "test"
              properties:
                teststrategy: "performance"
            #- name: "evaluation"
            #- name: "release"
            # - name: "environment-teardown"
    - name: "production"
      sequences:
        - name: "delivery"
          triggeredOn:
            - event: "perf-test.delivery.finished"
          tasks:
            - name: "deployment"
              properties:
                deploymentstrategy: "blue_green_service"
            - name: "release"

